[platformio]
default_envs = sensor-node

[env]
build_flags =
    -std=gnu++17
    -Wall -Werror
    -fno-exceptions

lib_extra_dirs =
    ../shared/domain
    ../shared/application
    ../shared/protocol

[env:sensor-node]
platform   = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board      = esp32-c6-devkitm-1
framework  = arduino
monitor_speed = 115200
upload_speed  = 921600
board_build.partitions = partitions.csv
board_build.flash_size = 4MB
extra_scripts = extra_script.py
build_flags =
    ${env.build_flags}
    -DGH_BUILD_TARGET=sensor_node
    -DZIGBEE_MODE_ED
    -Wno-unused-parameter
    -I lib/infrastructure/src/network
lib_deps =
    robtillaart/AM2315C@^0.2.2

[env:sensor-node-hwtest]
extends = env:sensor-node
build_flags =
    ${env:sensor-node.build_flags}
    -DGH_HW_TESTS=1
test_ignore =
test_filter = test_drivers/*

[env:sensor-node-native]
platform = native
build_flags =
    ${env.build_flags}
    -DGH_BUILD_TARGET=native
    -DUNITY_INCLUDE_DOUBLE
    -Wno-sign-conversion
    -I test
    -I lib/infrastructure/src/network
    -I ../shared/domain/src
    -I ../shared/protocol/src
test_framework = unity
test_ignore =
    test_drivers
    test_drivers/*
test_build_src = false
